name: CI/CD Pipeline

on:
  push:
    branches:
      - linux-vm-deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build MovieApiApp Docker image
      run: |
        docker build -t movieapiapp -f MovieApiApp/Dockerfile .
        docker tag movieapiapp viraj231/movieapiapp:latest
        docker push viraj231/movieapiapp:latest

    - name: Build frontend Docker image
      run: |
        docker build -t frontend ./frontend
        docker tag frontend viraj231/frontend:latest
        docker push viraj231/frontend:latest

    - name: Deploy to Linux VM
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.VM_IP }}
        username: ubuntu
        key: ${{ secrets.VM_SSH_PRIVATE_KEY}}
        script: |
          docker pull viraj231/movieapiapp:latest
          docker pull viraj231/frontend:latest

          docker stop movieapiapp_container || true
          docker rm movieapiapp_container || true
          docker stop frontend_container || true
          docker rm frontend_container || true

          docker run -d --name movieapiapp_container -p 6000:80 viraj231/movieapiapp:latest
          docker run -d --name frontend_container -p 90:80 viraj231/frontend:latest
