name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MovieApiApp Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./MovieApiApp/Dockerfile
          platforms: linux/arm64
          push: true
          tags: viraj231/movieapiapp:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          platforms: linux/arm64
          push: true
          tags: viraj231/frontend:latest
          build-args: |
            VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}

      - name: Build and push python recommender Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./movie-recommender/Dockerfile
          platforms: linux/arm64
          push: true
          tags: viraj231/python_recommender:latest
          build-args: |
            API_URL=${{ secrets.API_URL }}
            API_KEY=${{ secrets.OMDB_API_KEY }}

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Add VM to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Linux VM
        run: |
          ssh ubuntu@${{ secrets.VM_IP }} << EOF
          docker pull viraj231/movieapiapp:latest
          docker pull viraj231/frontend:latest
          docker pull viraj231/python_recommender:latest

          docker stop movieapiapp_container || true
          docker rm movieapiapp_container || true
          docker stop frontend_container || true
          docker rm frontend_container || true
          docker stop recommender_container || true
          docker rm recommender_container || true

          docker run -d --name movieapiapp_container \
          -p 6000:80 \
          -e ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}" \
          -e Jwt__Key="${{ secrets.JWT_SECRET_KEY }}" \
          -e Jwt__Issuer="https://moviepedia.virajdeveloper.online" \
          -e Jwt__Audience="https://moviepedia.virajdeveloper.online" \
          -e ApiKeyOmDb="${{ secrets.OMDB_API_KEY }}" \
          -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
          -e Google__Client_Id="${{ secrets.GOOGLE_CLIENT_ID }}" \
          -e Google__Client_Secret="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          -e ASPNETCORE_URLS=http://+:80 \
          viraj231/movieapiapp:latest

          docker run -d --name recommender_container \
          -p 5000:80 \
          -e API_URL="${{ secrets.API_URL }}" \
          -e API_KEY="${{ secrets.OMDB_API_KEY }}" \
          viraj231/python_recommender:latest

          docker run -d --name frontend_container \
            -p 90:80 \
            viraj231/frontend:latest
          EOF
